### ISSUE TITLE
Not picking up Disk errors

### ISSUE THREAD

**Issue by mvanlijden** [domalab/ha-unraid#3]
I currently have one disk (no 6) which has failed me. Unraid has disabled it, but due to parity the array is still working as it should.
![image](https://github.com/user-attachments/assets/98544411-e83a-4aa6-9ffb-4d98ad9073cc)
I however do not see anything on this in HA
![image](https://github.com/user-attachments/assets/29e48883-ab74-4ba4-9bee-560439b80b9d)
Is this a feature you have not yet implemented?

**Comment by mvanlijden** [comment]
Ok just saw on your HA community post that Extended disk health monitoring is on the future plans.

**Comment by domalab** [comment]
@mvanlijden will get the disk health feature sorted out as soon as possible. Hopefully before Christmas😊

**Comment by domalab** [comment]
@mvanlijden I have updated the code and added SMART features to show disk temps and status of the disk.

Just doing some tests with other updates before releasing a new version.

![Screenshot 2024-11-13 at 10 29 42 pm](https://github.com/user-attachments/assets/8b0db0f3-719d-4175-878c-7793c8fec160)

**Comment by mvanlijden** [comment]
Looking good! Love to put it in attributes as this doesn't pollute the long list of entities. I can pull it out for dashboard purposed with templating :)

**Comment by domalab** [comment]
@mvanlijden I release a new version that should show disk errors. Let me know if it works

**Comment by mvanlijden** [comment]
@domalab I don't think it is fully working yet. A lot of data is not interpreted correctly. My findings just now:

It does show Unraid parity details and status in de the attributes, but generic status is still unknown?
![image](https://github.com/user-attachments/assets/702a4470-6696-46bc-a4ab-69364d65aaf9)
Details on a healthy disk do show, but no temperature or smart results. This is only visible for disks which are spinned up.
For temperature that makes sense as it follows the behavior in Unraid. But maybe you should cache the temperature data?
![image](https://github.com/user-attachments/assets/57ab6d5f-1084-42bb-a839-d727535aaa33)
With a spinned up disk the smart check is read and the temp. But the last smart check
![image](https://github.com/user-attachments/assets/35e0c627-3273-48fb-bd1c-0af0969b568c)

Also a bigger issue is that the disk number do not match. I do not which sort they use, but they are mixed up. I first thought they used device sort (sda,sdb,sdc) instead of the disk numbering in Unraid. But that is also not the case. But I also means that the mounting points in HA are incorrect.
![image](https://github.com/user-attachments/assets/f4988aa5-a9d8-4382-bb09-8818909f06a6)
![image](https://github.com/user-attachments/assets/86a9e1f6-d65b-4bfd-8a05-b47e59872d22)

My failed disk (sde / disk 6), is split in details between disk 2 and 6 in HA:
![image](https://github.com/user-attachments/assets/a06c2135-13c9-401e-b172-bf24d90f3574)
![image](https://github.com/user-attachments/assets/1c69d17c-8410-4d57-97fe-e543511d3b15)
Device and model (and smart?) are linked in disk 2. Usage and size seem to be linked in disk 6 (the correct mounting point).
However none seem to pick up that the disk has failed.

Would any specific logging or print from Unraid help you? Please let me know what you need.

**Comment by domalab** [comment]
@mvanlijden Thanks for your feedback. Can you please run the following commands on your unraid server --> console and provide the outputs back to me?

Download Diagnostics file
![Screenshot 2024-11-16 at 6 33 56 am](https://github.com/user-attachments/assets/612050f6-5eba-47f4-b45b-2e947848a697)

# Get all disk information including SMART status
for disk in /dev/sd[a-z]; do
    echo "=== $disk ==="
    smartctl -a $disk
    echo "---"
done

# Get Unraid disk assignments and mapping
cat /boot/config/disk.cfg
ls -l /dev/disk/by-id/

# Get array configuration
cat /proc/mdstat
mdcmd status

# Get disk mount points and usage
df -h /mnt/disk*
mount | grep "mnt/disk"

# Get current disk states
hdparm -C /dev/sd[a-z]

# Get parity status
cat /proc/mdcmd

**Comment by domalab** [comment]
You can also run this script from Unraid --> User Scripts plugin to create disk diagnostic file.

[unraid_disk_diagnostics.sh.zip](https://github.com/user-attachments/files/17783421/unraid_disk_diagnostics.sh.zip)

**Comment by mvanlijden** [comment]
I'll do that today once I sit behind my laptop 👍🏻

**Comment by mvanlijden** [comment]
[Diagnostics output.txt](https://github.com/user-attachments/files/17786981/Diagnostics.output.txt)
Here you go

**Comment by domalab** [comment]
> [Diagnostics output.txt](https://github.com/user-attachments/files/17786981/Diagnostics.output.txt)
> 
> Here you go

Thank you. I'll see if I can sort out the disk mappings bug next week.

**Comment by domalab** [comment]
@mvanlijden I made updates to code to check disk mappings.

Feel free to test it on your system and let me know if it works for you.

I haven't officially released a new version yet as I'm still testing other fixes I implemented.

Copy the code files from unraid folder in repo to your custom_components\unraid folder and restart home assistant.

Best to test it on HA Dev instance if you have one.

**Comment by mvanlijden** [comment]
I changed the files (yesterday) and also removed and readded the integration, as the entity naming changed as well.
Things still do not match. See screenshots below. Number do not match Unraid.
Health status not visible on disk 6, nor on disk 5 (linked to device sde)

![image](https://github.com/user-attachments/assets/43284994-01b9-454c-86f9-1084bdfd2727)
![image](https://github.com/user-attachments/assets/8b32affa-0fa2-4f85-b3d1-8d8fabaa26ab)
![image](https://github.com/user-attachments/assets/9630668a-9db2-4233-9c1f-3e9f4199d1fe)
![image](https://github.com/user-attachments/assets/49aa1f34-2f1b-4d60-b3e6-d32fba0ae04f)

Also another find, it now does not show Dockers service as being active, even though it is?
Also it is not adding my dockers as entities anymore?

**Comment by domalab** [comment]
> I changed the files (yesterday) and also removed and readded the integration, as the entity naming changed as well.
> 
> Things still do not match. See screenshots below. Number do not match Unraid.
> 
> Health status not visible on disk 6, nor on disk 5 (linked to device sde)
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/43284994-01b9-454c-86f9-1084bdfd2727)
> 
> ![image](https://github.com/user-attachments/assets/8b32affa-0fa2-4f85-b3d1-8d8fabaa26ab)
> 
> ![image](https://github.com/user-attachments/assets/9630668a-9db2-4233-9c1f-3e9f4199d1fe)
> 
> ![image](https://github.com/user-attachments/assets/49aa1f34-2f1b-4d60-b3e6-d32fba0ae04f)
> 
> 
> 
> Also another find, it now does not show Dockers service as being active, even though it is?
> 
> Also it is not adding my dockers as entities anymore?
> 
> 

I spent a bit of time on understanding how the disk mapping in unraid works and updated the code.

**Comment by mvanlijden** [comment]
Not closed yet. Disk mapping has been improved and is now showing correct data for drives.
Health data as my failed disk however has never shown in HA... Maybe because it was not sent out?
I have included a new diagnostic file
[disk diagnostics.txt](https://github.com/user-attachments/files/18394862/disk.diagnostics.txt)

My drive is some revived (don't know how...). Doing a data rebuild now which i hope will make it, so I can extract all data properly.
![image](https://github.com/user-attachments/assets/61139d4c-4fb3-4c75-a8fb-06fe7c26f544)
![image](https://github.com/user-attachments/assets/c4262b15-de04-44f2-bac7-5a098c89a13a)

I do not see any the rebuild or warnings of the details on the disk in HA. 
Do see a attribute detail on the array status, but not on the main status or the array. It is rebuilding of course.
The array health is fine, which is correct. Due to one drive failing the parity has not yet broken.
![image](https://github.com/user-attachments/assets/11624eb9-fe5f-4db4-80f3-2693974e03ed)
![image](https://github.com/user-attachments/assets/2f9c0f7a-e417-4a24-9086-7d1c9e732f3b)
But nothing on any of the disk6 data.
![image](https://github.com/user-attachments/assets/ae4b2391-8013-4dee-9531-9c322888a74f)
![image](https://github.com/user-attachments/assets/48103e9c-9c13-4a24-ab9f-81c2ef0f9358)

**Comment by domalab** [comment]
@mvanlijden Can you please enable debug logging in the integration and then check the HA unraid logs for any info.

**Comment by domalab** [comment]
@mvanlijden I have a parity disk that shows an error
![Screenshot 2025-01-14 at 7 54 01 am](https://github.com/user-attachments/assets/56acf86e-b77b-48b5-a077-1aa97f2d0682)

But when I check the SMART report, last test result shows completed without error. 
![Screenshot 2025-01-14 at 7 54 49 am](https://github.com/user-attachments/assets/836235af-a7e3-44bc-a7cb-daad1604c6b5)

And the parity sensor reads SMART overall-health under Identity tab of disk as passed

![Screenshot 2025-01-14 at 8 43 07 am](https://github.com/user-attachments/assets/4441f985-b2d5-40be-8dc5-8e549d1f887b)

From what I can see under attributes the error / warning is for my disk is from UDMA CRC error count

![Screenshot 2025-01-14 at 8 46 44 am](https://github.com/user-attachments/assets/979dbbb8-1582-4b52-843c-c2b493287f5e)

From what I have read, SMART's "overall-health self-assessment" is actually quite basic and only looks for critical/catastrophic failures. It will typically only show "FAILED" when:

- The drive has completely failed or is about to fail imminently
- The drive has exceeded certain critical thresholds that the manufacturer has determined indicate imminent failure

However, this basic pass/fail assessment DOES NOT consider:

- Individual attribute failures (like the End-to-End errors we see on your disk 4 /dev/sdl)
- Reallocated sector counts (like the 208 sectors on your disk 6 /dev/sde)
- Temperature warnings
- Individual test failures
- Pending sector counts
- Error logs

**Comment by mvanlijden** [comment]
I indeed have the same with another Disk (nr 3). The drive is disabled from the array by Unraid due to read errors.
The SMART details show the individual items that are failing. The overall SMART status somehow still remains "Passed".
Based on this I would say that the health status that is shared to HA is effectively useless. I does not pick up on errors that could lead to a drive failure (as seen by Unraid disabling the drive for me). I cannot build automations on the drive health in HA as at that point the drive would have failed.
I also doubt if the data will be passed on to be honest, due to the fact that drives seem to need to be spinned up before data can be sent. If the drive failed and is spinned down, will HA even know?

![Image](https://github.com/user-attachments/assets/0e1669d9-70f1-4224-9b81-c395dad93f80)

![Image](https://github.com/user-attachments/assets/6cb7d876-d9fc-4dd3-b06c-499b5fdcc4ef)

![Image](https://github.com/user-attachments/assets/e8559984-a8ec-45c2-a36f-2d711297ca7b)

**Comment by mvanlijden** [comment]
In part of the debug logging I do see some details on my failed drive:
`'diskNumber.3': '3', 'diskName.3': 'md3p1', 'diskSize.3': '7814026532', 'diskState.3': '4', 'diskId.3': 'ST8000AS0002-1NA17Z_Z840584K', 'rdevNumber.3': '3', '**rdevStatus.3': 'DISK_DSBL'**, 'rdevName.3': 'sdg', 'rdevOffset.3': '64', 'rdevSize.3': '7814026532', 'rdevId.3': 'ST8000AS0002-1NA17Z_Z840584K', 'rdevReads.3': '1368649832', 'rdevWrites.3': '1965', 'rdevNumErrors.3': '2048',`
Status seems to represent Disk Disabled with NumErrors also being high.

Added the full debug log with a reload of the integration.
BTW the logging seems to be spammed with these messages as well:
_(MainThread) [custom_components.unraid.coordinator] Skipping invalid date: 1970 Jan  1 01:00:00_

`2025-02-07 13:57:16.546 DEBUG (MainThread) [custom_components.unraid.diagnostics.parity] Current array state: {'sbName': '/boot/config/super.dat', 'sbVersion': '2.9.4', 'sbCreated': '1543870133', 'sbUpdated': '1738814611', 'sbEvents': '422', 'sbState': '1', 'sbNumDisks': '10', 'sbLabel': '0781-5591-0001-260905122234', 'sbSynced': '1738766271', 'sbSynced2': '1738814611', 'sbSyncErrs': '0', 'sbSyncExit': '0', 'mdVersion': '2.9.33', 'mdState': 'STARTED', 'mdNumDisks': '9', 'mdNumDisabled': '2', 'mdNumReplaced': '0', 'mdNumInvalid': '2', 'mdNumMissing': '0', 'mdNumWrong': '0', 'mdNumNew': '0', 'mdSwapP': '0', 'mdSwapQ': '0', 'mdResyncAction': 'check', 'mdResyncSize': '9766436812', 'mdResyncCorr': '1', 'mdResync': '0', 'mdResyncPos': '0', 'mdResyncDt': '0', 'mdResyncDb': '0', 'diskNumber.0': '0', 'diskName.0': '', 'diskSize.0': '9766436812', 'diskState.0': '7', 'diskId.0': 'ST10000NM0016-1TT101_ZA21AXES', 'rdevNumber.0': '0', 'rdevStatus.0': 'DISK_OK', 'rdevName.0': 'sdf', 'rdevOffset.0': '64', 'rdevSize.0': '9766436812', 'rdevId.0': 'ST10000NM0016-1TT101_ZA21AXES', 'rdevReads.0': '2467524385', 'rdevWrites.0': '29068691', 'rdevNumErrors.0': '0', 'diskNumber.1': '1', 'diskName.1': 'md1p1', 'diskSize.1': '7814026532', 'diskState.1': '7', 'diskId.1': 'ST8000AS0002-1NA17Z_Z840BEJ9', 'rdevNumber.1': '1', 'rdevStatus.1': 'DISK_OK', 'rdevName.1': 'sdi', 'rdevOffset.1': '64', 'rdevSize.1': '7814026532', 'rdevId.1': 'ST8000AS0002-1NA17Z_Z840BEJ9', 'rdevReads.1': '1970862822', 'rdevWrites.1': '4376', 'rdevNumErrors.1': '0', 'diskNumber.2': '2', 'diskName.2': 'md2p1', 'diskSize.2': '7814026532', 'diskState.2': '7', 'diskId.2': 'ST8000AS0002-1NA17Z_Z840DNEL', 'rdevNumber.2': '2', 'rdevStatus.2': 'DISK_OK', 'rdevName.2': 'sdk', 'rdevOffset.2': '64', 'rdevSize.2': '7814026532', 'rdevId.2': 'ST8000AS0002-1NA17Z_Z840DNEL', 'rdevReads.2': '1972138408', 'rdevWrites.2': '1687628', 'rdevNumErrors.2': '0', 'diskNumber.3': '3', 'diskName.3': 'md3p1', 'diskSize.3': '7814026532', 'diskState.3': '4', 'diskId.3': 'ST8000AS0002-1NA17Z_Z840584K', 'rdevNumber.3': '3', '**rdevStatus.3': 'DISK_DSBL'**, 'rdevName.3': 'sdg', 'rdevOffset.3': '64', 'rdevSize.3': '7814026532', 'rdevId.3': 'ST8000AS0002-1NA17Z_Z840584K', 'rdevReads.3': '1368649832', 'rdevWrites.3': '1965', 'rdevNumErrors.3': '2048', 'diskNumber.4': '4', 'diskName.4': 'md4p1', 'diskSize.4': '7814026532', 'diskState.4': '7', 'diskId.4': 'ST8000VN0022-2EL112_ZA19P9M4', 'rdevNumber.4': '4', 'rdevStatus.4': 'DISK_OK', 'rdevName.4': 'sdl', 'rdevOffset.4': '64', 'rdevSize.4': '7814026532', 'rdevId.4': 'ST8000VN0022-2EL112_ZA19P9M4', 'rdevReads.4': '2018180966', 'rdevWrites.4': '27372137', 'rdevNumErrors.4': '0', 'diskNumber.5': '5', 'diskName.5': 'md5p1', 'diskSize.5': '4883770532', 'diskState.5': '7', 'diskId.5': 'ST5000DM000-1FK178_W4J1PXVY', 'rdevNumber.5': '5', 'rdevStatus.5': 'DISK_OK', 'rdevName.5': 'sdd', 'rdevOffset.5': '64', 'rdevSize.5': '4883770532', 'rdevId.5': 'ST5000DM000-1FK178_W4J1PXVY', 'rdevReads.5': '1227645068', 'rdevWrites.5': '623', 'rdevNumErrors.5': '0', 'diskNumber.6': '6', 'diskName.6': 'md6p1', 'diskSize.6': '4883770532', 'diskState.6': '7', 'diskId.6': 'ST5000DM000-1FK178_W4J1FVPE', 'rdevNumber.6': '6', 'rdevStatus.6': 'DISK_OK', 'rdevName.6': 'sde', 'rdevOffset.6': '64', 'rdevSize.6': '4883770532', 'rdevId.6': 'ST5000DM000-1FK178_W4J1FVPE', 'rdevReads.6': '1226945143', 'rdevWrites.6': '672', 'rdevNumErrors.6': '0', 'diskNumber.7': '7', 'diskName.7': 'md7p1', 'diskSize.7': '9766436812', 'diskState.7': '7', 'diskId.7': 'ST10000NE0008-2JM101_ZJ002YPM', 'rdevNumber.7': '7', 'rdevStatus.7': 'DISK_OK', 'rdevName.7': 'sdj', 'rdevOffset.7': '64', 'rdevSize.7': '9766436812', 'rdevId.7': 'ST10000NE0008-2JM101_ZJ002YPM', 'rdevReads.7': '2451898559', 'rdevWrites.7': '674', 'rdevNumErrors.7': '0', 'diskNumber.8': '8', 'diskName.8': 'md8p1', 'diskSize.8': '9766436812', 'diskState.8': '7', 'diskId.8': 'MG06ACA10TE_41U0A0C2FR7H', 'rdevNumber.8': '8', 'rdevStatus.8': 'DISK_OK', 'rdevName.8': 'sdh', 'rdevOffset.8': '64', 'rdevSize.8': '9766436812', 'rdevId.8': 'MG06ACA10TE_41U0A0C2FR7H', 'rdevReads.8': '2454470695', 'rdevWrites.8': '1457', 'rdevNumErrors.8': '0', 'diskNumber.9': '9', 'diskName.9': '', 'diskSize.9': '0', 'diskState.9': '0', 'diskId.9': '', 'rdevNumber.9': '9', 'rdevStatus.9': 'DISK_NP', 'rdevName.9': '', 'rdevOffset.9': '0', 'rdevSize.9': '0', 'rdevId.9': '', 'rdevReads.9': '0', 'rdevWrites.9': '0', 'rdevNumErrors.9': '0', 'diskNumber.10': '10', 'diskName.10': '', 'diskSize.10': '0', 'diskState.10': '0', 'diskId.10': '', 'rdevNumber.10': '10', 'rdevStatus.10': 'DISK_NP', 'rdevName.10': '', 'rdevOffset.10': '0', 'rdevSize.10': '0', 'rdevId.10': '', 'rdevReads.10': '0', 'rdevWrites.10': '0', 'rdevNumErrors.10': '0', 'diskNumber.11': '11', 'diskName.11': '', 'diskSize.11': '0', 'diskState.11': '0', 'diskId.11': '', 'rdevNumber.11': '11', 'rdevStatus.11': 'DISK_NP', 'rdevName.11': '', 'rdevOffset.11': '0', 'rdevSize.11': '0', 'rdevId.11': '', 'rdevReads.11': '0', 'rdevWrites.11': '0', 'rdevNumErrors.11': '0', 'diskNumber.12': '12', 'diskName.12': '', 'diskSize.12': '0', 'diskState.12': '0', 'diskId.12': '', 'rdevNumber.12': '12', 'rdevStatus.12': 'DISK_NP', 'rdevName.12': '', 'rdevOffset.12': '0', 'rdevSize.12': '0', 'rdevId.12': '', 'rdevReads.12': '0', 'rdevWrites.12': '0', 'rdevNumErrors.12': '0', 'diskNumber.13': '13', 'diskName.13': '', 'diskSize.13': '0', 'diskState.13': '0', 'diskId.13': '', 'rdevNumber.13': '13', 'rdevStatus.13': 'DISK_NP', 'rdevName.13': '', 'rdevOffset.13': '0', 'rdevSize.13': '0', 'rdevId.13': '', 'rdevReads.13': '0', 'rdevWrites.13': '0', 'rdevNumErrors.13': '0', 'diskNumber.14': '14', 'diskName.14': '', 'diskSize.14': '0', 'diskState.14': '0', 'diskId.14': '', 'rdevNumber.14': '14', 'rdevStatus.14': 'DISK_NP', 'rdevName.14': '', 'rdevOffset.14': '0', 'rdevSize.14': '0', 'rdevId.14': '', 'rdevReads.14': '0', 'rdevWrites.14': '0', 'rdevNumErrors.14': '0', 'diskNumber.15': '15', 'diskName.15': '', 'diskSize.15': '0', 'diskState.15': '0', 'diskId.15': '', 'rdevNumber.15': '15', 'rdevStatus.15': 'DISK_NP', 'rdevName.15': '', 'rdevOffset.15': '0', 'rdevSize.15': '0', 'rdevId.15': '', 'rdevReads.15': '0', 'rdevWrites.15': '0', 'rdevNumErrors.15': '0', 'diskNumber.16': '16', 'diskName.16': '', 'diskSize.16': '0', 'diskState.16': '0', 'diskId.16': '', 'rdevNumber.16': '16', 'rdevStatus.16': 'DISK_NP', 'rdevName.16': '', 'rdevOffset.16': '0', 'rdevSize.16': '0', 'rdevId.16': '', 'rdevReads.16': '0', 'rdevWrites.16': '0', 'rdevNumErrors.16': '0', 'diskNumber.17': '17', 'diskName.17': '', 'diskSize.17': '0', 'diskState.17': '0', 'diskId.17': '', 'rdevNumber.17': '17', 'rdevStatus.17': 'DISK_NP', 'rdevName.17': '', 'rdevOffset.17': '0', 'rdevSize.17': '0', 'rdevId.17': '', 'rdevReads.17': '0', 'rdevWrites.17': '0', 'rdevNumErrors.17': '0', 'diskNumber.18': '18', 'diskName.18': '', 'diskSize.18': '0', 'diskState.18': '0', 'diskId.18': '', 'rdevNumber.18': '18', 'rdevStatus.18': 'DISK_NP', 'rdevName.18': '', 'rdevOffset.18': '0', 'rdevSize.18': '0', 'rdevId.18': '', 'rdevReads.18': '0', 'rdevWrites.18': '0', 'rdevNumErrors.18': '0', 'diskNumber.19': '19', 'diskName.19': '', 'diskSize.19': '0', 'diskState.19': '0', 'diskId.19': '', 'rdevNumber.19': '19', 'rdevStatus.19': 'DISK_NP', 'rdevName.19': '', 'rdevOffset.19': '0', 'rdevSize.19': '0', 'rdevId.19': '', 'rdevReads.19': '0', 'rdevWrites.19': '0', 'rdevNumErrors.19': '0', 'diskNumber.20': '20', 'diskName.20': '', 'diskSize.20': '0', 'diskState.20': '0', 'diskId.20': '', 'rdevNumber.20': '20', 'rdevStatus.20': 'DISK_NP', 'rdevName.20': '', 'rdevOffset.20': '0', 'rdevSize.20': '0', 'rdevId.20': '', 'rdevReads.20': '0', 'rdevWrites.20': '0', 'rdevNumErrors.20': '0', 'diskNumber.21': '21', 'diskName.21': '', 'diskSize.21': '0', 'diskState.21': '0', 'diskId.21': '', 'rdevNumber.21': '21', 'rdevStatus.21': 'DISK_NP', 'rdevName.21': '', 'rdevOffset.21': '0', 'rdevSize.21': '0', 'rdevId.21': '', 'rdevReads.21': '0', 'rdevWrites.21': '0', 'rdevNumErrors.21': '0', 'diskNumber.22': '22', 'diskName.22': '', 'diskSize.22': '0', 'diskState.22': '0', 'diskId.22': '', 'rdevNumber.22': '22', 'rdevStatus.22': 'DISK_NP', 'rdevName.22': '', 'rdevOffset.22': '0', 'rdevSize.22': '0', 'rdevId.22': '', 'rdevReads.22': '0', 'rdevWrites.22': '0', 'rdevNumErrors.22': '0', 'diskNumber.23': '23', 'diskName.23': '', 'diskSize.23': '0', 'diskState.23': '0', 'diskId.23': '', 'rdevNumber.23': '23', 'rdevStatus.23': 'DISK_NP', 'rdevName.23': '', 'rdevOffset.23': '0', 'rdevSize.23': '0', 'rdevId.23': '', 'rdevReads.23': '0', 'rdevWrites.23': '0', 'rdevNumErrors.23': '0', 'diskNumber.24': '24', 'diskName.24': '', 'diskSize.24': '0', 'diskState.24': '0', 'diskId.24': '', 'rdevNumber.24': '24', 'rdevStatus.24': 'DISK_NP', 'rdevName.24': '', 'rdevOffset.24': '0', 'rdevSize.24': '0', 'rdevId.24': '', 'rdevReads.24': '0', 'rdevWrites.24': '0', 'rdevNumErrors.24': '0', 'diskNumber.25': '25', 'diskName.25': '', 'diskSize.25': '0', 'diskState.25': '0', 'diskId.25': '', 'rdevNumber.25': '25', 'rdevStatus.25': 'DISK_NP', 'rdevName.25': '', 'rdevOffset.25': '0', 'rdevSize.25': '0', 'rdevId.25': '', 'rdevReads.25': '0', 'rdevWrites.25': '0', 'rdevNumErrors.25': '0', 'diskNumber.26': '26', 'diskName.26': '', 'diskSize.26': '0', 'diskState.26': '0', 'diskId.26': '', 'rdevNumber.26': '26', 'rdevStatus.26': 'DISK_NP', 'rdevName.26': '', 'rdevOffset.26': '0', 'rdevSize.26': '0', 'rdevId.26': '', 'rdevReads.26': '0', 'rdevWrites.26': '0', 'rdevNumErrors.26': '0', 'diskNumber.27': '27', 'diskName.27': '', 'diskSize.27': '0', 'diskState.27': '0', 'diskId.27': '', 'rdevNumber.27': '27', 'rdevStatus.27': 'DISK_NP', 'rdevName.27': '', 'rdevOffset.27': '0', 'rdevSize.27': '0', 'rdevId.27': '', 'rdevReads.27': '0', 'rdevWrites.27': '0', 'rdevNumErrors.27': '0', 'diskNumber.28': '28', 'diskName.28': '', 'diskSize.28': '0', 'diskState.28': '0', 'diskId.28': '', 'rdevNumber.28': '28', 'rdevStatus.28': 'DISK_NP', 'rdevName.28': '', 'rdevOffset.28': '0', 'rdevSize.28': '0', 'rdevId.28': '', 'rdevReads.28': '0', 'rdevWrites.28': '0', 'rdevNumErrors.28': '0', 'diskNumber.29': '29', 'diskName.29': '', 'diskSize.29': '0', 'diskState.29': '4', 'diskId.29': '', 'rdevNumber.29': '29', 'rdevStatus.29': 'DISK_NP_DSBL', 'rdevName.29': '', 'rdevOffset.29': '0', 'rdevSize.29': '0', 'rdevId.29': '', 'rdevReads.29': '0', 'rdevWrites.29': '0', 'rdevNumErrors.29': '0', 'parity_history': {'date': '2025-02-06 05:03:31', 'duration': '13 hours, 25 minutes, 40 seconds', 'speed': '206.89 MB/s', 'status': 'Success', 'errors': 0, 'type': 'check', 'size': '9766436812'}}
`

and from this section as well
`2025-02-07 13:56:57.980 DEBUG (MainThread) [custom_components.unraid.api.disk_mapping] Parsed disk mappings from disks.ini: {'parity': {'name': 'parity', 'idx': '0', 'device': 'sdf', 'id': 'ST10000NM0016-1TT101_ZA21AXES', 'transport': 'ata', 'size': '9766436812', 'status': 'DISK_OK', 'format': 'GPT: 4KiB-aligned', 'rotational': '1', 'discard': '0', 'removable': '0', 'spundown': '0', 'temp': '21', 'numReads': '2467524385', 'numWrites': '29068691', 'numErrors': '0', 'type': 'Parity', 'color': 'green-on', 'spindownDelay': '15', 'spinupGroup': '', 'idSb': 'ST10000NM0016-1TT101_ZA21AXES', 'sizeSb': '9766436812'}, 'disk1': {'name': 'disk1', 'idx': '1', 'device': 'sdi', 'id': 'ST8000AS0002-1NA17Z_Z840BEJ9', 'transport': 'ata', 'size': '7814026532', 'status': 'DISK_OK', 'format': 'GPT: 4KiB-aligned', 'rotational': '1', 'discard': '0', 'removable': '0', 'spundown': '0', 'temp': '23', 'numReads': '1970862822', 'numWrites': '4376', 'numErrors': '0', 'type': 'Data', 'color': 'green-on', 'spindownDelay': '-1', 'spinupGroup': '', 'idSb': 'ST8000AS0002-1NA17Z_Z840BEJ9', 'sizeSb': '7814026532', 'deviceSb': 'md1p1', 'luksState': '0', 'fsType': 'xfs', 'fsStatus': 'Mounted', 'autotrim': 'off', 'compression': 'off', 'warning': '', 'critical': '', 'exportable': 'no', 'comment': '', 'fsColor': 'yellow-on', 'fsSize': '7811939620', 'fsFree': '1219724664', 'fsUsed': '6592214956'}, 'disk2': {'name': 'disk2', 'idx': '2', 'device': 'sdk', 'id': 'ST8000AS0002-1NA17Z_Z840DNEL', 'transport': 'ata', 'size': '7814026532', 'status': 'DISK_OK', 'format': 'GPT: 4KiB-aligned', 'rotational': '1', 'discard': '0', 'removable': '0', 'spundown': '0', 'temp': '19', 'numReads': '1972138408', 'numWrites': '1687628', 'numErrors': '0', 'type': 'Data', 'color': 'green-on', 'spindownDelay': '-1', 'spinupGroup': '', 'idSb': 'ST8000AS0002-1NA17Z_Z840DNEL', 'sizeSb': '7814026532', 'deviceSb': 'md2p1', 'luksState': '0', 'fsType': 'xfs', 'fsStatus': 'Mounted', 'autotrim': 'off', 'compression': 'off', 'warning': '', 'critical': '', 'exportable': 'no', 'comment': '', 'fsColor': 'yellow-on', 'fsSize': '7811939620', 'fsFree': '1218358660', 'fsUsed': '6593580960'}, 'disk3': {'name': 'disk3', 'idx': '3', 'device': 'sdg', 'id': 'ST8000AS0002-1NA17Z_Z840584K', 'transport': 'ata', 'size': '7814026532', **'status': 'DISK_DSBL'**, 'format': 'GPT: 4KiB-aligned', 'rotational': '1', 'discard': '0', 'removable': '0', 'spundown': '0', 'temp': '23', 'numReads': '1368649832', 'numWrites': '1965', 'numErrors': '2048', 'type': 'Data', **'color': 'red-on'**, 'spindownDelay': '-1', 'spinupGroup': '', 'idSb': 'ST8000AS0002-1NA17Z_Z840584K', 'sizeSb': '7814026532', 'deviceSb': 'md3p1', 'luksState': '0', 'fsType': 'xfs', 'fsStatus': 'Mounted', 'autotrim': 'off', 'compression': 'off', 'warning': '', 'critical': '', 'exportable': 'no', 'comment': '', 'fsColor': 'yellow-on', 'fsSize': '7811939620', 'fsFree': '459278216', 'fsUsed': '7352661404'}, `

[home-assistant_unraid_2025-02-07T12-57-55.229Z.log](https://github.com/user-attachments/files/18706998/home-assistant_unraid_2025-02-07T12-57-55.229Z.log)
