### ISSUE TITLE
[BUG] Missing sensors & attributes in v2025.06.02

### ISSUE THREAD

**Issue by CZonin** [domalab/ha-unraid#83]
### Checklist (required)

- [x] I have **searched existing open and closed issues** to ensure this is not a duplicate.  
- [x] I have **reproduced the issue** on the latest version to confirm it still exists.

---

### Describe the Bug

After updating to v2025.06.02 some of the sensors and attributes that were previously available are no longer working. For each disk in my array, the temperature attribute is now showing `N/A`. Additionally, my second cache pool is not showing up as a sensor at all anymore.

---

### Expected Behavior

The temperature sensors for the disks in my array will show the proper data as they previously did. Also, a sensor will be available for my second cache pool as it previously was.

---

### Screenshots

![Image](https://github.com/user-attachments/assets/0f77a9d7-2bbf-4e48-a843-eb351ba9991b)

---

### Debug Log

Where can this be found after enabling debug logging for the integration?

**Comment by ruaan-deysel** [comment]
@CZonin Thanks for pointing this out. This should be fixed now. I'll release a new version in a couple of days

**Comment by CZonin** [comment]
Thanks @domalab , and thanks for all the work on the new release!

**Comment by ruaan-deysel** [comment]
> Thanks [@domalab](https://github.com/domalab) , and thanks for all the work on the new release!

Should be fixed now. Works fine for me

**Comment by CZonin** [comment]
Temperature sensors are all now there, but I'm still missing my second cache pool. I do have a space in the same of the pool, could that be the cause?

Edit: It doesn't have a space, but it does have a special character `-`

**Comment by ruaan-deysel** [comment]
> Temperature sensors are all now there, but I'm still missing my second cache pool. I do have a space in the same of the pool, could that be the cause?
> 
> Edit: It doesn't have a space, but it does have a special character `-`

Any errors in the logs? You can also enable debug logs for integration and you filter for cache to see what the error is.

**Comment by CZonin** [comment]
> > Temperature sensors are all now there, but I'm still missing my second cache pool. I do have a space in the same of the pool, could that be the cause?
> > Edit: It doesn't have a space, but it does have a special character `-`
> 
> Any errors in the logs? You can also enable debug logs for integration and you filter for cache to see what the error is.

No errors. Here's the logs filtered by cache:

```
2025-06-05 18:53:07.285 DEBUG (MainThread) [custom_components.unraid.api.disk_operations] Created SmartDataManager and DiskStateManager, cleared MD cache
2025-06-05 18:53:07.285 DEBUG (MainThread) [custom_components.unraid.api.cache_manager] CacheManager initialized with max size: 50.0 MB, cleanup interval: 300 seconds
2025-06-05 18:53:10.145 DEBUG (MainThread) [custom_components.unraid.api.disk_state] Found and cached device path for disk1: /dev/sdi
2025-06-05 18:53:10.318 DEBUG (MainThread) [custom_components.unraid.api.disk_state] Found and cached device path for disk2: /dev/sdf
2025-06-05 18:53:10.490 DEBUG (MainThread) [custom_components.unraid.api.disk_state] Found and cached device path for disk3: /dev/sdg
2025-06-05 18:53:10.645 DEBUG (MainThread) [custom_components.unraid.api.disk_state] Found and cached device path for disk4: /dev/sde
2025-06-05 18:53:10.820 DEBUG (MainThread) [custom_components.unraid.api.disk_state] Found and cached device path for disk5: /dev/sdd
2025-06-05 18:53:10.939 DEBUG (MainThread) [custom_components.unraid.api.disk_state] Found and cached device path for disk6: /dev/sdj
2025-06-05 18:53:11.042 DEBUG (MainThread) [custom_components.unraid.api.disk_state] Executing mount command for cache: findmnt -n -o SOURCE /mnt/cache
2025-06-05 18:53:11.045 DEBUG (MainThread) [custom_components.unraid.api.disk_state] Mount command result for cache: exit_code=0, stdout='/dev/sdb1'
2025-06-05 18:53:11.045 DEBUG (MainThread) [custom_components.unraid.api.disk_state] Found and cached device path for cache: /dev/sdb1
2025-06-05 18:53:11.045 DEBUG (MainThread) [custom_components.unraid.api.disk_operations] Disk cache state from DiskStateManager: active
2025-06-05 18:53:14.977 DEBUG (MainThread) [custom_components.unraid.api.disk_state] Using cached device path for disk1: /dev/sdi
2025-06-05 18:53:14.988 DEBUG (MainThread) [custom_components.unraid.api.usb_detection] Using cached USB detection for /dev/sdi
2025-06-05 18:53:14.988 DEBUG (MainThread) [custom_components.unraid.api.smart_operations] Using cached SMART data for /dev/sdi (age: 0:00:04.832042)
2025-06-05 18:53:14.988 DEBUG (MainThread) [custom_components.unraid.api.disk_state] Using cached device path for disk2: /dev/sdf
2025-06-05 18:53:14.999 DEBUG (MainThread) [custom_components.unraid.api.usb_detection] Using cached USB detection for /dev/sdf
2025-06-05 18:53:14.999 DEBUG (MainThread) [custom_components.unraid.api.smart_operations] Using cached SMART data for /dev/sdf (age: 0:00:04.669457)
2025-06-05 18:53:14.999 DEBUG (MainThread) [custom_components.unraid.api.disk_state] Using cached device path for disk3: /dev/sdg
2025-06-05 18:53:15.011 DEBUG (MainThread) [custom_components.unraid.api.usb_detection] Using cached USB detection for /dev/sdg
2025-06-05 18:53:15.011 DEBUG (MainThread) [custom_components.unraid.api.smart_operations] Using cached SMART data for /dev/sdg (age: 0:00:04.509246)
2025-06-05 18:53:15.011 DEBUG (MainThread) [custom_components.unraid.api.disk_state] Using cached device path for disk4: /dev/sde
2025-06-05 18:53:15.022 DEBUG (MainThread) [custom_components.unraid.api.usb_detection] Using cached USB detection for /dev/sde
2025-06-05 18:53:15.022 DEBUG (MainThread) [custom_components.unraid.api.smart_operations] Using cached SMART data for /dev/sde (age: 0:00:04.366075)
2025-06-05 18:53:15.022 DEBUG (MainThread) [custom_components.unraid.api.disk_state] Using cached device path for disk5: /dev/sdd
2025-06-05 18:53:15.032 DEBUG (MainThread) [custom_components.unraid.api.usb_detection] Using cached USB detection for /dev/sdd
2025-06-05 18:53:15.032 DEBUG (MainThread) [custom_components.unraid.api.smart_operations] Using cached SMART data for /dev/sdd (age: 0:00:04.201046)
2025-06-05 18:53:15.032 DEBUG (MainThread) [custom_components.unraid.api.disk_state] Using cached device path for disk6: /dev/sdj
2025-06-05 18:53:15.042 DEBUG (MainThread) [custom_components.unraid.api.usb_detection] Using cached USB detection for /dev/sdj
2025-06-05 18:53:15.043 DEBUG (MainThread) [custom_components.unraid.api.smart_operations] Using cached SMART data for /dev/sdj (age: 0:00:04.091760)
2025-06-05 18:53:15.048 DEBUG (MainThread) [custom_components.unraid.api.disk_state] Using cached device path for cache: /dev/sdb1
2025-06-05 18:53:15.048 DEBUG (MainThread) [custom_components.unraid.api.disk_operations] Disk cache state from DiskStateManager: active
2025-06-05 18:53:15.048 DEBUG (MainThread) [custom_components.unraid.api.usb_detection] Using cached USB detection for /dev/sdb1
2025-06-05 18:53:15.048 DEBUG (MainThread) [custom_components.unraid.api.smart_operations] Using cached SMART data for /dev/sdb1 (age: 0:00:04.002943)
2025-06-05 18:53:15.314 DEBUG (MainThread) [custom_components.unraid.api.disk_state] Using cached device path for disk1: /dev/sdi
2025-06-05 18:53:15.324 DEBUG (MainThread) [custom_components.unraid.api.usb_detection] Using cached USB detection for /dev/sdi
2025-06-05 18:53:15.324 DEBUG (MainThread) [custom_components.unraid.api.smart_operations] Using cached SMART data for /dev/sdi (age: 0:00:05.168327)
2025-06-05 18:53:15.324 DEBUG (MainThread) [custom_components.unraid.api.disk_state] Using cached device path for disk2: /dev/sdf
2025-06-05 18:53:15.336 DEBUG (MainThread) [custom_components.unraid.api.usb_detection] Using cached USB detection for /dev/sdf
2025-06-05 18:53:15.336 DEBUG (MainThread) [custom_components.unraid.api.smart_operations] Using cached SMART data for /dev/sdf (age: 0:00:05.006559)
2025-06-05 18:53:15.336 DEBUG (MainThread) [custom_components.unraid.api.disk_state] Using cached device path for disk3: /dev/sdg
2025-06-05 18:53:15.347 DEBUG (MainThread) [custom_components.unraid.api.usb_detection] Using cached USB detection for /dev/sdg
2025-06-05 18:53:15.347 DEBUG (MainThread) [custom_components.unraid.api.smart_operations] Using cached SMART data for /dev/sdg (age: 0:00:04.845331)
2025-06-05 18:53:15.347 DEBUG (MainThread) [custom_components.unraid.api.disk_state] Using cached device path for disk4: /dev/sde
2025-06-05 18:53:15.359 DEBUG (MainThread) [custom_components.unraid.api.usb_detection] Using cached USB detection for /dev/sde
2025-06-05 18:53:15.359 DEBUG (MainThread) [custom_components.unraid.api.smart_operations] Using cached SMART data for /dev/sde (age: 0:00:04.702965)
2025-06-05 18:53:15.359 DEBUG (MainThread) [custom_components.unraid.api.disk_state] Using cached device path for disk5: /dev/sdd
2025-06-05 18:53:15.370 DEBUG (MainThread) [custom_components.unraid.api.usb_detection] Using cached USB detection for /dev/sdd
2025-06-05 18:53:15.370 DEBUG (MainThread) [custom_components.unraid.api.smart_operations] Using cached SMART data for /dev/sdd (age: 0:00:04.539044)
2025-06-05 18:53:15.370 DEBUG (MainThread) [custom_components.unraid.api.disk_state] Using cached device path for disk6: /dev/sdj
2025-06-05 18:53:15.381 DEBUG (MainThread) [custom_components.unraid.api.usb_detection] Using cached USB detection for /dev/sdj
2025-06-05 18:53:15.381 DEBUG (MainThread) [custom_components.unraid.api.smart_operations] Using cached SMART data for /dev/sdj (age: 0:00:04.430333)
2025-06-05 18:53:15.387 DEBUG (MainThread) [custom_components.unraid.api.disk_state] Using cached device path for cache: /dev/sdb1
2025-06-05 18:53:15.387 DEBUG (MainThread) [custom_components.unraid.api.disk_operations] Disk cache state from DiskStateManager: active
2025-06-05 18:53:15.388 DEBUG (MainThread) [custom_components.unraid.api.usb_detection] Using cached USB detection for /dev/sdb1
2025-06-05 18:53:15.388 DEBUG (MainThread) [custom_components.unraid.api.smart_operations] Using cached SMART data for /dev/sdb1 (age: 0:00:04.342619)
2025-06-05 18:53:20.273 DEBUG (MainThread) [custom_components.unraid.coordinator] Data update complete in 12.96s. Cache hits: 0, misses: 8, hit rate: 0.0%
2025-06-05 18:53:20.275 INFO (MainThread) [custom_components.unraid.helpers] Detected potential pool: cache, mount: /mnt/cache, filesystem: btrfs
2025-06-05 18:53:20.275 INFO (MainThread) [custom_components.unraid.helpers] Detected pool: cache, filesystem: btrfs, mount: /mnt/cache, size: 3.64 TB, used: 72.03 GB
2025-06-05 18:53:20.275 DEBUG (MainThread) [custom_components.unraid.sensors.base] Base Entity initialized | unique_id: unraid_cz-server_pool_cache_usage | name: Cache Usage | description.key: pool_cache_usage
2025-06-05 18:53:20.275 DEBUG (MainThread) [custom_components.unraid.sensors.registry] Added SSD sensor: cache
2025-06-05 18:53:20.276 DEBUG (MainThread) [custom_components.unraid.sensors.registry] System stats keys: dict_keys(['array_state', 'cpu_usage', 'cpu_cores', 'cpu_model', 'cpu_arch', 'memory_usage', 'uptime', 'temperature_data', 'boot_usage', 'cache_usage', 'log_filesystem', 'docker_vdisk', 'intel_gpu', 'ups_info', 'array_usage', 'individual_disks', 'disk_mapping', 'disk_info', 'network_stats'])
2025-06-05 18:53:20.297 DEBUG (MainThread) [custom_components.unraid.diagnostics.base] Binary Sensor initialized | unique_id: unraid_cz-server_disk_health_cache | name: Cache Health | description.key: disk_health_cache
2025-06-05 18:53:20.297 DEBUG (MainThread) [custom_components.unraid.diagnostics.pool] Initialized pool disk sensor | name: cache | type: SATA | device: /dev/sdb1 | serial: unknown
2025-06-05 18:53:20.297 INFO (MainThread) [custom_components.unraid.binary_sensor] Added pool disk sensor: cache
2025-06-05 18:53:20.305 DEBUG (MainThread) [custom_components.unraid.diagnostics.parity] Updated cached disk size for sdh: 16000900661248 bytes
2025-06-05 18:53:20.308 DEBUG (MainThread) [custom_components.unraid.diagnostics.pool] Updated spin down delay for pool cache to 30 minutes
2025-06-05 18:53:20.308 DEBUG (MainThread) [custom_components.unraid.diagnostics.pool] Starting SMART analysis for pool cache with data: {'name': 'cache', 'mount_point': '/mnt/cache', 'total': 4000785960960, 'used': 77339250688, 'free': 3919497031680, 'percentage': 1.9, 'state': 'active', 'smart_status': 'Passed', 'temperature': 36, 'device': '/dev/sdb1', 'filesystem': 'btrfs', 'power_on_hours': None}
2025-06-05 18:53:20.308 DEBUG (MainThread) [custom_components.unraid.diagnostics.pool] Pool cache current state: active
2025-06-05 18:53:20.308 DEBUG (MainThread) [custom_components.unraid.diagnostics.pool] Pool cache SMART status: passed
2025-06-05 18:53:20.308 DEBUG (MainThread) [custom_components.unraid.diagnostics.pool] Processing SATA attributes for pool cache
2025-06-05 18:53:20.308 DEBUG (MainThread) [custom_components.unraid.diagnostics.pool] No problems found for pool cache
```

The device is `nvme0n1` in Unraid. Here's the logs filtered for that:

```
2025-06-05 18:53:10.138 DEBUG (MainThread) [custom_components.unraid.api.disk_operations] Found serial for nvme0n1: 244634802542
2025-06-05 18:53:10.138 DEBUG (MainThread) [custom_components.unraid.api.disk_operations] Found block device nvme0n1: transport=nvme, type=disk
2025-06-05 18:53:10.138 DEBUG (MainThread) [custom_components.unraid.api.disk_operations] Found block device `-nvme0n1p1: transport=nvme, type=part
2025-06-05 18:53:14.977 DEBUG (MainThread) [custom_components.unraid.api.disk_operations] Found serial for nvme0n1: 244634802542
2025-06-05 18:53:14.977 DEBUG (MainThread) [custom_components.unraid.api.disk_operations] Found block device nvme0n1: transport=nvme, type=disk
2025-06-05 18:53:14.977 DEBUG (MainThread) [custom_components.unraid.api.disk_operations] Found block device `-nvme0n1p1: transport=nvme, type=part
2025-06-05 18:53:15.313 DEBUG (MainThread) [custom_components.unraid.api.disk_operations] Found serial for nvme0n1: 244634802542
2025-06-05 18:53:15.313 DEBUG (MainThread) [custom_components.unraid.api.disk_operations] Found block device nvme0n1: transport=nvme, type=disk
2025-06-05 18:53:15.314 DEBUG (MainThread) [custom_components.unraid.api.disk_operations] Found block device `-nvme0n1p1: transport=nvme, type=part
```

**Comment by ruaan-deysel** [comment]
Should be fixed now in latest update. Added regex detection pattern to pickup and type of custom pool name

**Comment by CZonin** [comment]
> Should be fixed now in latest update. Added regex detection pattern to pickup and type of custom pool name

That did it, thanks again @domalab !
