### ISSUE TITLE
Important Sensors missing after last update

### ISSUE THREAD

**Issue by Protarios** [domalab/ha-unraid#85]
The last update seems to have changed the naming of most sensors.

This has broken all dashboards, but can be repaired.

But what really is a problem, is that two of the most important sensors are gone now:

UPS total consumption (I used that for energy monitoring my NAS)
And Array Health (only the individial disk health status is left, not the array/pool health)

**Comment by ruaan-deysel** [comment]
> The last update seems to have changed the naming of most sensors.
> 
> This has broken all dashboards, but can be repaired.
> 
> But what really is a problem, is that two of the most important sensors are gone now:
> 
> UPS total consumption (I used that for energy monitoring my NAS) And Array Health (only the individial disk health status is left, not the array/pool health)

Thanks for reporting the issues. 

I fixed the UPS energy and Array Health sensor in the latest update this should now show up in HA and can be added back to Energy dashboard.

**Comment by Protarios** [comment]
Thats great to know. In the current version in HACS (2025.06.05) the sensors are missing.
Do you refer to that version, or is there an update coming?

**Comment by ruaan-deysel** [comment]
> Thats great to know. In the current version in HACS (2025.06.05) the sensors are missing. Do you refer to that version, or is there an update coming?

This one

https://github.com/domalab/ha-unraid/releases/tag/v2025.06.10

**Comment by Protarios** [comment]
Just was able to do the update.
Everything working again.
Thanks!!

**Comment by Protarios** [comment]
Sorry to come back to this.
UPS Server Energy Sensor is back, but it stays at 0 kWh.
Last update stays also always at time of last Home Assistant Reboot.

**Comment by ruaan-deysel** [comment]
> Sorry to come back to this. UPS Server Energy Sensor is back, but it stays at 0 kWh. Last update stays also always at time of last Home Assistant Reboot.

Thanks for pointing it out. It's fixed now. 

![Image](https://github.com/user-attachments/assets/3b3a4267-06e0-401c-aa34-6253c03cc8ba)

**Comment by domalab** [comment]
> > Sorry to come back to this. UPS Server Energy Sensor is back, but it stays at 0 kWh. Last update stays also always at time of last Home Assistant Reboot.
> 
> Thanks for pointing it out. It's fixed now.
> 
> ![Image](https://github.com/user-attachments/assets/3b3a4267-06e0-401c-aa34-6253c03cc8ba)

**Comment by ZoXx** [comment]
Hey,
**pool_cache_usage** and **pool_cache_health** are still missing?
